### PR TITLE
Add electron app to main

### PR DESCRIPTION
**Pull request by crazy4pi314**
Setting this up so I can track issues to close b4 merging this.

### CODE REVIEW

**Comment by petersterne** [comment]
I see that we commented out the lines that automatically create TXT and VTT files (and there's nothing about creating SRT files, which we might want to copy from a more up-to-date version of whisper, see #40). Is that because @oenu's Electron app is just going to handle the transcriptions and allow users to export them, so there's no need for the script to create them directly?

**Comment by sawhney17** [comment]
I believe that would be the _**ideal**_ workflow. Not sure if that's currently being done.

**Comment by crazy4pi314** [comment]
Yeah I didn't hook them up bc I didn't think the script would be responsible for file manipulation. It certainly can and that may be good for testing, but was initially just trying to get it to work 😅

**Comment by harrislapiroff** [comment]
We're functionally doing all of our work on the `electron` branch now and it is basically our `main` branch. I haven't thoroughly reviewed the code. I do think we should do a full code audit at some point, but for the moment I think we should stop pretending this is a feature branch and merge it into main where it belongs.

That way we can return to a more normal PR review and merge flow.

**Review by harrislapiroff — APPROVED** [review]

**Pull request merged**
