### PR TITLE
Electron UI

### PR DESCRIPTION
**Pull request by crazy4pi314**
Setting this up as a draft @oenu so it's easier for folks to find for playing around :)

### CODE REVIEW

**Comment by petersterne** [comment]
We should probably update the Readme to explain how to get the Electron app running.

**Comment by petersterne** [comment]
If I run the Electron app and go to settings and click the toggle switch to enable the large models, the app crashes. Here's the error message in the console:

`serializableStateInvariantMiddleware.ts:194 A non-serializable value was detected in an action, in the path: `payload`. Value: SyntheticBaseEvent {_reactName: 'onChange', _targetInst: null, type: 'change', nativeEvent: PointerEvent, target: input#mantine-44pt7i4wl.mantine-rpvocz.mantine-Switch-input, …} 
Take a look at the logic that dispatched this action:  {type: 'settings/setDisplayLanguage', payload: SyntheticBaseEvent} 
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants) 
(To allow non-serializable values see: https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data)`

**Comment by petersterne** [comment]
Rather than keeping this as a draft PR that merges into the `main` branch, I'm going to merge this into the `electron` branch.

**Comment by oenu** [comment]
@Stage-Whisper/developers Requesting pull into branch, will pull issue branches from here

**Comment by oenu** [comment]
Also when merging please squash, my personal commit style is much too much for a public repo

**Comment by oenu** [comment]
Ready for merge

**Review by petersterne — APPROVED** [review]
Looks good. Running `yarn` and then `yarn dev` from the app directory successfully launches the Electron app.

**Comment by oenu** [comment]
Jsut a note, when this gets pulled to main can we squash the commit history?

**Pull request merged**
